# Add sudo package and overwrite of default entrypoint
USER root
RUN apk add --no-cache sudo && \
	echo 'Defaults env_keep += "JAVA_* JENKINS_* REF COPY_REFERENCE_FILE_LOG"' >> /etc/sudoers

COPY resources/ayudadigital-jenkins-dind.sh /usr/local/bin/ayudadigital-jenkins-dind.sh
ENTRYPOINT ["/sbin/tini", "--", "/usr/local/bin/ayudadigital-jenkins-dind.sh"]
